// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Parameters for a split request.
///
/// [source] supports the following forms:
/// - `http://...` or `https://...` — remote image download
/// - `file:///...` or absolute path — local file split directly (no download)
///
/// Generated class from Pigeon that represents data sent in messages.
struct SplitRequest: Hashable {
  /// Image source (URL or local file path).
  var source: String
  /// Maximum height (in pixels) of each chunk.
  var maxChunkHeight: Int64
  /// Previously cached ETag, used for conditional GET. If the server
  /// responds 304 Not Modified, the cache is reused.
  var cachedEtag: String? = nil
  /// Previously cached Last-Modified header, used for conditional GET.
  var cachedLastModified: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SplitRequest? {
    let source = pigeonVar_list[0] as! String
    let maxChunkHeight = pigeonVar_list[1] as! Int64
    let cachedEtag: String? = nilOrValue(pigeonVar_list[2])
    let cachedLastModified: String? = nilOrValue(pigeonVar_list[3])

    return SplitRequest(
      source: source,
      maxChunkHeight: maxChunkHeight,
      cachedEtag: cachedEtag,
      cachedLastModified: cachedLastModified
    )
  }
  func toList() -> [Any?] {
    return [
      source,
      maxChunkHeight,
      cachedEtag,
      cachedLastModified,
    ]
  }
  static func == (lhs: SplitRequest, rhs: SplitRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.source, rhs.source) && deepEqualsMessages(lhs.maxChunkHeight, rhs.maxChunkHeight) && deepEqualsMessages(lhs.cachedEtag, rhs.cachedEtag) && deepEqualsMessages(lhs.cachedLastModified, rhs.cachedLastModified)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SplitRequest")
    deepHashMessages(value: source, hasher: &hasher)
    deepHashMessages(value: maxChunkHeight, hasher: &hasher)
    deepHashMessages(value: cachedEtag, hasher: &hasher)
    deepHashMessages(value: cachedLastModified, hasher: &hasher)
  }
}

/// Result of a split operation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SplitResult: Hashable {
  /// Ordered list of chunk file paths (chunk_0.jpg, chunk_1.jpg, ...).
  var paths: [String]
  /// Whether the result came from cache (no network or decode work).
  var fromCache: Bool
  /// ETag returned by the server, to be passed back on the next request.
  var etag: String? = nil
  /// Last-Modified returned by the server.
  var lastModified: String? = nil
  /// Actual height of each chunk in [paths]. SplitImageView uses this to
  /// compute precise placeholder sizes (no jank when scrolling).
  var chunkHeights: [Int64]
  /// Width of the original image. Used by SplitImageView for aspect ratio.
  var imageWidth: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SplitResult? {
    let paths = pigeonVar_list[0] as! [String]
    let fromCache = pigeonVar_list[1] as! Bool
    let etag: String? = nilOrValue(pigeonVar_list[2])
    let lastModified: String? = nilOrValue(pigeonVar_list[3])
    let chunkHeights = pigeonVar_list[4] as! [Int64]
    let imageWidth = pigeonVar_list[5] as! Int64

    return SplitResult(
      paths: paths,
      fromCache: fromCache,
      etag: etag,
      lastModified: lastModified,
      chunkHeights: chunkHeights,
      imageWidth: imageWidth
    )
  }
  func toList() -> [Any?] {
    return [
      paths,
      fromCache,
      etag,
      lastModified,
      chunkHeights,
      imageWidth,
    ]
  }
  static func == (lhs: SplitResult, rhs: SplitResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.paths, rhs.paths) && deepEqualsMessages(lhs.fromCache, rhs.fromCache) && deepEqualsMessages(lhs.etag, rhs.etag) && deepEqualsMessages(lhs.lastModified, rhs.lastModified) && deepEqualsMessages(lhs.chunkHeights, rhs.chunkHeights) && deepEqualsMessages(lhs.imageWidth, rhs.imageWidth)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SplitResult")
    deepHashMessages(value: paths, hasher: &hasher)
    deepHashMessages(value: fromCache, hasher: &hasher)
    deepHashMessages(value: etag, hasher: &hasher)
    deepHashMessages(value: lastModified, hasher: &hasher)
    deepHashMessages(value: chunkHeights, hasher: &hasher)
    deepHashMessages(value: imageWidth, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SplitRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return SplitResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SplitRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? SplitResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart → Native call interface.
///
/// Splits large images into smaller chunks using platform-native bitmap decoders.
///
/// ## Why native splitting is needed
///
/// Flutter's Skia/Impeller rendering engine has a GPU texture size limit.
/// The exact value depends on the device — typically between 4096 and 16384
/// pixels. Images exceeding this limit are forcefully downscaled, causing
/// visible distortion. Use [getMaxTextureSize] to query the device's actual
/// limit at runtime instead of hardcoding a value.
///
/// ## Platform implementations
///
/// - **Android**: Uses `BitmapRegionDecoder` for region-based decoding
///   without loading the full image into memory.
/// - **iOS**: Uses `CGImageSource` + `CGImageSourceCreateImageAtIndex` with
///   region cropping. Memory profile matches Android (no full decode upfront).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ImageSplitterApi {
  /// Splits an image into chunks of [SplitRequest.maxChunkHeight] or less.
  ///
  /// Error codes:
  /// - `INVALID_ARGS`: Empty source, non-positive maxChunkHeight, or malformed URL
  /// - `WIDTH_TOO_LARGE`: Image width exceeds maxChunkHeight (horizontal split unsupported)
  /// - `DOWNLOAD_ERROR`: Network error, 404, or timeout
  /// - `FILE_NOT_FOUND`: Local file path does not exist
  /// - `DECODE_ERROR`: Unsupported format or corrupt image
  /// - `SPLIT_ERROR`: Error during the split (disk full, IO failure, etc.)
  func splitImage(request: SplitRequest, completion: @escaping (Result<SplitResult, Error>) -> Void)
  /// Deletes all cached split images. Returns the number of files deleted.
  func clearCache(completion: @escaping (Result<Int64, Error>) -> Void)
  /// Queries the device's maximum GPU texture size.
  ///
  /// - Android: GLES `GL_MAX_TEXTURE_SIZE`
  /// - iOS: Metal `MTLDevice.maxTextureSize2D`
  ///
  /// Returns a safe fallback (4096) if the query fails. Use this value as
  /// the default for [SplitRequest.maxChunkHeight] when the caller does not
  /// supply one.
  func getMaxTextureSize(completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ImageSplitterApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ImageSplitterApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ImageSplitterApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Splits an image into chunks of [SplitRequest.maxChunkHeight] or less.
    ///
    /// Error codes:
    /// - `INVALID_ARGS`: Empty source, non-positive maxChunkHeight, or malformed URL
    /// - `WIDTH_TOO_LARGE`: Image width exceeds maxChunkHeight (horizontal split unsupported)
    /// - `DOWNLOAD_ERROR`: Network error, 404, or timeout
    /// - `FILE_NOT_FOUND`: Local file path does not exist
    /// - `DECODE_ERROR`: Unsupported format or corrupt image
    /// - `SPLIT_ERROR`: Error during the split (disk full, IO failure, etc.)
    let splitImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_splitter.ImageSplitterApi.splitImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      splitImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SplitRequest
        api.splitImage(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      splitImageChannel.setMessageHandler(nil)
    }
    /// Deletes all cached split images. Returns the number of files deleted.
    let clearCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_splitter.ImageSplitterApi.clearCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCacheChannel.setMessageHandler { _, reply in
        api.clearCache { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearCacheChannel.setMessageHandler(nil)
    }
    /// Queries the device's maximum GPU texture size.
    ///
    /// - Android: GLES `GL_MAX_TEXTURE_SIZE`
    /// - iOS: Metal `MTLDevice.maxTextureSize2D`
    ///
    /// Returns a safe fallback (4096) if the query fails. Use this value as
    /// the default for [SplitRequest.maxChunkHeight] when the caller does not
    /// supply one.
    let getMaxTextureSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_splitter.ImageSplitterApi.getMaxTextureSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMaxTextureSizeChannel.setMessageHandler { _, reply in
        api.getMaxTextureSize { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMaxTextureSizeChannel.setMessageHandler(nil)
    }
  }
}
