// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.hrjy6278.image_splitter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Parameters for a split request.
 *
 * [source] supports the following forms:
 * - `http://...` or `https://...` — remote image download
 * - `file:///...` or absolute path — local file split directly (no download)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SplitRequest (
  /** Image source (URL or local file path). */
  val source: String,
  /** Maximum height (in pixels) of each chunk. */
  val maxChunkHeight: Long,
  /**
   * Previously cached ETag, used for conditional GET. If the server
   * responds 304 Not Modified, the cache is reused.
   */
  val cachedEtag: String? = null,
  /** Previously cached Last-Modified header, used for conditional GET. */
  val cachedLastModified: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SplitRequest {
      val source = pigeonVar_list[0] as String
      val maxChunkHeight = pigeonVar_list[1] as Long
      val cachedEtag = pigeonVar_list[2] as String?
      val cachedLastModified = pigeonVar_list[3] as String?
      return SplitRequest(source, maxChunkHeight, cachedEtag, cachedLastModified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      maxChunkHeight,
      cachedEtag,
      cachedLastModified,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SplitRequest
    return MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.maxChunkHeight, other.maxChunkHeight) && MessagesPigeonUtils.deepEquals(this.cachedEtag, other.cachedEtag) && MessagesPigeonUtils.deepEquals(this.cachedLastModified, other.cachedLastModified)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxChunkHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cachedEtag)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cachedLastModified)
    return result
  }
}

/**
 * Result of a split operation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SplitResult (
  /** Ordered list of chunk file paths (chunk_0.jpg, chunk_1.jpg, ...). */
  val paths: List<String>,
  /** Whether the result came from cache (no network or decode work). */
  val fromCache: Boolean,
  /** ETag returned by the server, to be passed back on the next request. */
  val etag: String? = null,
  /** Last-Modified returned by the server. */
  val lastModified: String? = null,
  /**
   * Actual height of each chunk in [paths]. SplitImageView uses this to
   * compute precise placeholder sizes (no jank when scrolling).
   */
  val chunkHeights: List<Long>,
  /** Width of the original image. Used by SplitImageView for aspect ratio. */
  val imageWidth: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SplitResult {
      val paths = pigeonVar_list[0] as List<String>
      val fromCache = pigeonVar_list[1] as Boolean
      val etag = pigeonVar_list[2] as String?
      val lastModified = pigeonVar_list[3] as String?
      val chunkHeights = pigeonVar_list[4] as List<Long>
      val imageWidth = pigeonVar_list[5] as Long
      return SplitResult(paths, fromCache, etag, lastModified, chunkHeights, imageWidth)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      paths,
      fromCache,
      etag,
      lastModified,
      chunkHeights,
      imageWidth,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SplitResult
    return MessagesPigeonUtils.deepEquals(this.paths, other.paths) && MessagesPigeonUtils.deepEquals(this.fromCache, other.fromCache) && MessagesPigeonUtils.deepEquals(this.etag, other.etag) && MessagesPigeonUtils.deepEquals(this.lastModified, other.lastModified) && MessagesPigeonUtils.deepEquals(this.chunkHeights, other.chunkHeights) && MessagesPigeonUtils.deepEquals(this.imageWidth, other.imageWidth)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.paths)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fromCache)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.etag)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lastModified)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.chunkHeights)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.imageWidth)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SplitRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SplitResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SplitRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SplitResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart → Native call interface.
 *
 * Splits large images into smaller chunks using platform-native bitmap decoders.
 *
 * ## Why native splitting is needed
 *
 * Flutter's Skia/Impeller rendering engine has a GPU texture size limit.
 * The exact value depends on the device — typically between 4096 and 16384
 * pixels. Images exceeding this limit are forcefully downscaled, causing
 * visible distortion. Use [getMaxTextureSize] to query the device's actual
 * limit at runtime instead of hardcoding a value.
 *
 * ## Platform implementations
 *
 * - **Android**: Uses `BitmapRegionDecoder` for region-based decoding
 *   without loading the full image into memory.
 * - **iOS**: Uses `CGImageSource` + `CGImageSourceCreateImageAtIndex` with
 *   region cropping. Memory profile matches Android (no full decode upfront).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ImageSplitterApi {
  /**
   * Splits an image into chunks of [SplitRequest.maxChunkHeight] or less.
   *
   * Error codes:
   * - `INVALID_ARGS`: Empty source, non-positive maxChunkHeight, or malformed URL
   * - `WIDTH_TOO_LARGE`: Image width exceeds maxChunkHeight (horizontal split unsupported)
   * - `DOWNLOAD_ERROR`: Network error, 404, or timeout
   * - `FILE_NOT_FOUND`: Local file path does not exist
   * - `DECODE_ERROR`: Unsupported format or corrupt image
   * - `SPLIT_ERROR`: Error during the split (disk full, IO failure, etc.)
   */
  fun splitImage(request: SplitRequest, callback: (Result<SplitResult>) -> Unit)
  /** Deletes all cached split images. Returns the number of files deleted. */
  fun clearCache(callback: (Result<Long>) -> Unit)
  /**
   * Queries the device's maximum GPU texture size.
   *
   * - Android: GLES `GL_MAX_TEXTURE_SIZE`
   * - iOS: Metal `MTLDevice.maxTextureSize2D`
   *
   * Returns a safe fallback (4096) if the query fails. Use this value as
   * the default for [SplitRequest.maxChunkHeight] when the caller does not
   * supply one.
   */
  fun getMaxTextureSize(callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by ImageSplitterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ImageSplitterApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ImageSplitterApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_splitter.ImageSplitterApi.splitImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SplitRequest
            api.splitImage(requestArg) { result: Result<SplitResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_splitter.ImageSplitterApi.clearCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearCache{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_splitter.ImageSplitterApi.getMaxTextureSize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getMaxTextureSize{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
