// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Parameters for a split request.
///
/// [source] supports the following forms:
/// - `http://...` or `https://...` — remote image download
/// - `file:///...` or absolute path — local file split directly (no download)
class SplitRequest {
  SplitRequest({
    required this.source,
    required this.maxChunkHeight,
    this.cachedEtag,
    this.cachedLastModified,
  });

  /// Image source (URL or local file path).
  String source;

  /// Maximum height (in pixels) of each chunk.
  int maxChunkHeight;

  /// Previously cached ETag, used for conditional GET. If the server
  /// responds 304 Not Modified, the cache is reused.
  String? cachedEtag;

  /// Previously cached Last-Modified header, used for conditional GET.
  String? cachedLastModified;

  List<Object?> _toList() {
    return <Object?>[
      source,
      maxChunkHeight,
      cachedEtag,
      cachedLastModified,
    ];
  }

  Object encode() {
    return _toList();  }

  static SplitRequest decode(Object result) {
    result as List<Object?>;
    return SplitRequest(
      source: result[0]! as String,
      maxChunkHeight: result[1]! as int,
      cachedEtag: result[2] as String?,
      cachedLastModified: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SplitRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(source, other.source) && _deepEquals(maxChunkHeight, other.maxChunkHeight) && _deepEquals(cachedEtag, other.cachedEtag) && _deepEquals(cachedLastModified, other.cachedLastModified);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Result of a split operation.
class SplitResult {
  SplitResult({
    required this.paths,
    required this.fromCache,
    this.etag,
    this.lastModified,
    required this.chunkHeights,
    required this.imageWidth,
  });

  /// Ordered list of chunk file paths (chunk_0.jpg, chunk_1.jpg, ...).
  List<String> paths;

  /// Whether the result came from cache (no network or decode work).
  bool fromCache;

  /// ETag returned by the server, to be passed back on the next request.
  String? etag;

  /// Last-Modified returned by the server.
  String? lastModified;

  /// Actual height of each chunk in [paths]. SplitImageView uses this to
  /// compute precise placeholder sizes (no jank when scrolling).
  List<int> chunkHeights;

  /// Width of the original image. Used by SplitImageView for aspect ratio.
  int imageWidth;

  List<Object?> _toList() {
    return <Object?>[
      paths,
      fromCache,
      etag,
      lastModified,
      chunkHeights,
      imageWidth,
    ];
  }

  Object encode() {
    return _toList();  }

  static SplitResult decode(Object result) {
    result as List<Object?>;
    return SplitResult(
      paths: (result[0]! as List<Object?>).cast<String>(),
      fromCache: result[1]! as bool,
      etag: result[2] as String?,
      lastModified: result[3] as String?,
      chunkHeights: (result[4]! as List<Object?>).cast<int>(),
      imageWidth: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SplitResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(paths, other.paths) && _deepEquals(fromCache, other.fromCache) && _deepEquals(etag, other.etag) && _deepEquals(lastModified, other.lastModified) && _deepEquals(chunkHeights, other.chunkHeights) && _deepEquals(imageWidth, other.imageWidth);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SplitRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is SplitResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SplitRequest.decode(readValue(buffer)!);
      case 130:
        return SplitResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart → Native call interface.
///
/// Splits large images into smaller chunks using platform-native bitmap decoders.
///
/// ## Why native splitting is needed
///
/// Flutter's Skia/Impeller rendering engine has a GPU texture size limit.
/// The exact value depends on the device — typically between 4096 and 16384
/// pixels. Images exceeding this limit are forcefully downscaled, causing
/// visible distortion. Use [getMaxTextureSize] to query the device's actual
/// limit at runtime instead of hardcoding a value.
///
/// ## Platform implementations
///
/// - **Android**: Uses `BitmapRegionDecoder` for region-based decoding
///   without loading the full image into memory.
/// - **iOS**: Uses `CGImageSource` + `CGImageSourceCreateImageAtIndex` with
///   region cropping. Memory profile matches Android (no full decode upfront).
class ImageSplitterApi {
  /// Constructor for [ImageSplitterApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ImageSplitterApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Splits an image into chunks of [SplitRequest.maxChunkHeight] or less.
  ///
  /// Error codes:
  /// - `INVALID_ARGS`: Empty source, non-positive maxChunkHeight, or malformed URL
  /// - `WIDTH_TOO_LARGE`: Image width exceeds maxChunkHeight (horizontal split unsupported)
  /// - `DOWNLOAD_ERROR`: Network error, 404, or timeout
  /// - `FILE_NOT_FOUND`: Local file path does not exist
  /// - `DECODE_ERROR`: Unsupported format or corrupt image
  /// - `SPLIT_ERROR`: Error during the split (disk full, IO failure, etc.)
  Future<SplitResult> splitImage(SplitRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.image_splitter.ImageSplitterApi.splitImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as SplitResult;
  }

  /// Deletes all cached split images. Returns the number of files deleted.
  Future<int> clearCache() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.image_splitter.ImageSplitterApi.clearCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Queries the device's maximum GPU texture size.
  ///
  /// - Android: GLES `GL_MAX_TEXTURE_SIZE`
  /// - iOS: Metal `MTLDevice.maxTextureSize2D`
  ///
  /// Returns a safe fallback (4096) if the query fails. Use this value as
  /// the default for [SplitRequest.maxChunkHeight] when the caller does not
  /// supply one.
  Future<int> getMaxTextureSize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.image_splitter.ImageSplitterApi.getMaxTextureSize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }
}
